name: mlcf
channels:
  - moble
  - https://conda.anaconda.org/paesanilab
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py35_1
  - intel-openmp=2019.1=144
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py35h7dd41cf_0
  - mkl_random=1.0.1=py35h4414c95_1
  - ncurses=6.1=he6710b0_1
  - numpy=1.15.2=py35h1d66e8a_0
  - numpy-base=1.15.2=py35h81de0dd_0
  - openssl=1.0.2p=h14c3975_0
  - pip=10.0.1=py35_0
  - python=3.5.6=hc3d631a_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.2.0=py35_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.31.1=py35_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - quaternion=2018.03.06.20.03.47=py35_0
  - spherical_functions=2016.11.07.dev17494408=py35_0
  - pip:
    - absl-py==0.6.1
    - ase==3.17.0
    - astor==0.7.1
    - backcall==0.1.0
    - click==7.0
    - cycler==0.10.0
    - cython==0.29.2
    - decorator==4.3.0
    - flask==1.0.2
    - gast==0.2.0
    - grpcio==1.17.1
    - h5py==2.8.0
    - ipykernel==5.1.0
    - ipyparallel==6.2.3
    - ipython==7.2.0
    - ipython-genutils==0.2.0
    - itsdangerous==1.1.0
    - jedi==0.13.2
    - jinja2==2.10
    - jupyter-client==5.2.4
    - jupyter-core==4.4.0
    - keras==2.2.4
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - kiwisolver==1.0.1
    - llvmlite==0.26.0
    - markdown==3.0.1
    - markupsafe==1.1.0
    - matplotlib==3.0.2
    - mpmath==1.1.0
    - numba==0.41.0
    - numpy-quaternion==2018.3.7.1.24.10
    - pandas==0.23.4
    - parso==0.3.1
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - prompt-toolkit==2.0.7
    - protobuf==3.6.1
    - ptyprocess==0.6.0
    - pygments==2.3.1
    - pyparsing==2.3.0
    - python-dateutil==2.7.5
    - pytz==2018.7
    - pyyaml==3.13
    - pyzmq==17.1.2
    - scikit-learn==0.20.2
    - scipy==1.2.0
    - six==1.12.0
    - sympy==1.3
    - tensorboard==1.12.1
    - tensorflow==1.12.0
    - termcolor==1.1.0
    - tornado==5.1.1
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - werkzeug==0.14.1
prefix: /home/sebastian/miniconda3/envs/mlcf

